name: Publish HttpClientUtility NuGet Package

on:
  push:
    branches: [main] # Trigger on pushes to the main branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to check out the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x" # Changed from 8.x to 9.0.x

      - name: Restore dependencies
        run: dotnet restore WebSpark.HttpClientUtility.sln

      - name: Build solution
        run: dotnet build WebSpark.HttpClientUtility.sln --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack WebSpark.HttpClientUtility/WebSpark.HttpClientUtility.csproj --configuration Release --no-build --output ./nupkg

      - name: Publish NuGet package
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
